name: Job Monitoring

on:
  schedule:
    - cron: '0 7 * * *' # 9:00 за Києвом
  workflow_dispatch: # Кнопка для ручного запуску

jobs:
  run_bot:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: pip install requests beautifulsoup4
      - name: Run bot
       env:
          WORK_UA_COOKIE: ${{ secrets.WORK_UA_COOKIE }}
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }} # Додати цей рядок
        run: python bot.py
